name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  intl: ^0.18.0
flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^2.0.1