name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  charts_common:
    path: ../charts_common/
  collection: ^1.17.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  logging: ^1.1.1
  meta: ^1.8.0


dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  test: ^1.22.0
  flutter_lints: ^2.0.1
